services:
  # ! the dev mode in docker container is not stable
  #   paideia:
  #     image: oven/bun:latest
  #     container_name: paideia
  #     ports:
  #       - "3000:3000"
  #     volumes:
  #       - .:/home/bun/app
  #       - ./node_modules:/home/bun/app/node_modules
  #     working_dir: /home/bun/app
  #     environment:
  #       - NODE_ENV=development
  #       - DATABASE_URL=postgresql://paideia:paideia_password@postgres:5432/paideia_db
  #       - S3_URL=http://minio:9000
  #       - S3_ACCESS_KEY=paideia_minio
  #       - S3_SECRET_KEY=paideia_minio_secret
  #     command: sh -c "bun install && bun --watch ./server/index.ts"
  #     networks:
  #       paideia_net:
  #         ipv4_address: 172.28.0.2
  #     depends_on:
  #       - postgres
  #       - minio

  postgres:
    image: postgres:15
    container_name: paideia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: paideia
      POSTGRES_PASSWORD: paideia_password
      POSTGRES_DB: paideia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      paideia_net:
        ipv4_address: 172.28.0.3

  minio:
    image: minio/minio:latest
    container_name: paideia_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: paideia_minio
      MINIO_ROOT_PASSWORD: paideia_minio_secret
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      paideia_net:
        ipv4_address: 172.28.0.4

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: drizzle-gateway
    restart: unless-stopped
    ports:
      - "4983:4983"
    environment:
      PORT: 4983
      STORE_PATH: ./app
      MASTERPASS: your_master_password
      DATABASE_URL: postgresql://paideia:paideia_password@postgres:5432/paideia_db
    volumes:
      - drizzle-gateway:/app
    networks:
      paideia_net:
        ipv4_address: 172.28.0.5
    depends_on:
      - postgres

volumes:
  minio_data:
  postgres_data:
  drizzle-gateway:

networks:
  paideia_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
