services:
  paideia:
    image: oven/bun:latest
    container_name: paideia
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/home/app
      - ./node_modules:/home/app/node_modules
      - .react-router:/home/app/.react-router
    working_dir: /home/app
    environment:
      - NODE_ENV=development
    command: sh -c "bun install && bun --watch ./server/index.ts"
    networks:
      paideia_net:
        ipv4_address: 172.28.0.2
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: paideia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: paideia
      POSTGRES_PASSWORD: paideia_password
      POSTGRES_DB: paideia_db
    ports:
      - "5432:5432"
    networks:
      paideia_net:
        ipv4_address: 172.28.0.3

networks:
  paideia_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
